name: tasks_app_acl
description: Tasks App made by ACharLuk

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  sqflite:
  path:
  share_plus:
  file_picker:
  url_launcher:
  fluttericon:
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - resources/